packages:
- apps/*
- packages/*
onlyBuiltDependencies:
- '@parcel/watcher'
- '@prisma/engines'
- '@swc/core'
- esbuild
- prisma
- sharp
- simple-git-hooks
overrides:
  drizzle-kit: 0.31.10
  preact: 10.28.2
  js-yaml: ^4.1.1
  '@types/hast': ^3.0.5
packageExtensions:
  '@hookform/resolvers':
    peerDependencies:
      zod: ^3.25.0 || ^4.0.0
    peerDependenciesMeta:
      zod:
        optional: true
