name: Auto Tag

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ['main']

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create tag
        id: tag
        run: echo "TAG=v${{ github.run_number }}.${{ github.run_number }}.${{ github.run_number }}" >> $GITHUB_ENV

      - name: Push tag
        run: |
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config user.name "${GITHUB_ACTOR}"
          VERSION=$(node -pe "require('./package.json').version")
          git tag $VERSION
          git push origin $VERSION
